return {
  ["workshop-1079538195"]={
    configuration_options={
      beebox=true,
      birdcage=true,
      cartographydesk=true,
      cookpot=true,
      dragonflychest=true,
      dragonflyfurnace=true,
      endtable=true,
      firesuppressor=true,
      icebox=true,
      lightning_rod=true,
      meatrack=true,
      modsupport=false,
      moondial=true,
      mushroom_farm=true,
      mushroom_light=true,
      nightlight=true,
      perdshrine=true,
      pottedfern=true,
      rainometer=true,
      researchlab=true,
      researchlab2=true,
      researchlab3=true,
      researchlab4=true,
      resurrectionstatue=true,
      saltlick=true,
      scarecrow=true,
      sculptingtable=true,
      succulent_potted=true,
      townportal=true,
      treasurechest=true,
      wardrobe=true,
      winterometer=true 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-2321974509"]={ configuration_options={ SIB=false, SSB=false }, enabled=true },
  ["workshop-2477889104"]={
    configuration_options={
      BADGE_BG_BRIGHTNESS=60,
      BADGE_BG_OPACITY=100,
      COLOR_DOMESTICATION_DEFAULT="WHITE",
      COLOR_DOMESTICATION_ORNERY="ORANGE",
      COLOR_DOMESTICATION_PUDGY="PURPLE",
      COLOR_DOMESTICATION_RIDER="BLUE",
      COLOR_OBEDIENCE="RED",
      COLOR_TIMER="GREEN",
      ClientConfig=false,
      EnableSounds=false,
      GapModifier=0,
      HEALTH_BADGE_CLEAR_BG=false,
      HungerThreshold=10,
      OffsetX=0,
      OffsetXFine=0,
      OffsetXMult=1,
      OffsetY=0,
      OffsetYFine=0,
      OffsetYMult=1,
      SEPARATOR_BADGE_COLORS=1,
      SEPARATOR_BADGE_SETTINGS=1,
      SEPARATOR_GENERAL=1,
      SEPARATOR_POSITIONING_X=1,
      SEPARATOR_POSITIONING_Y=1,
      Scale=1,
      ShowByDefault=true,
      Theme="TheForge",
      ToggleKey="KEY_T" 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-356398534"]={ configuration_options={  }, enabled=true },
  ["workshop-356930882"]={
    configuration_options={ uses=10000000, uses2=10000000, uses3=10000000 },
    enabled=true 
  },
  ["workshop-358749986"]={
    configuration_options={ IndicatorSize=3, MaxIndicator=7000, PlayerIndicators=1 },
    enabled=true 
  },
  ["workshop-361994110"]={
    configuration_options={ HAT_DECAY=false, RELEASE_BEES=false, SPRING_BEES=true },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={
    configuration_options={
      STACK_SIZE_LARGEITEM=99,
      STACK_SIZE_MEDITEM=99,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=99 
    },
    enabled=true 
  },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-396026892"]={ configuration_options={ OPT_DIFFICULTY=1 }, enabled=true },
  ["workshop-463952377"]={ configuration_options={ DFV_Language="EN" }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-588560555"]={ configuration_options={  }, enabled=true },
  ["workshop-604761020"]={
    configuration_options={
      RUOYINXIAN=false,
      SHENGDANSHI=false,
      baoshibaolv=1,
      blue_baoshi=1,
      er_shuoming=0,
      green_baoshi=1,
      huangjinbaolv=1,
      marble_suipian=1,
      orange_baoshi=1,
      purple_baoshi=1,
      red_baoshi=1,
      shishengzhang=0,
      shitoubaolv=1,
      thulecite_xiukuang=1,
      wajuecishu=2,
      yellow_baoshi=1,
      yi_shuoming=0 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  },
  ["workshop-679636739"]={ configuration_options={  }, enabled=true } 
}